version: 0.2


phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      # Install dependencies
      - pip install -r requirements.txt
  post_build:
    commands:
      # Deploy to AWS Elastic Beanstalk
      - aws elasticbeanstalk create-application-version --application-name callensights-app --version-label $CODEBUILD_RESOLVED_SOURCE_VERSION --source-bundle S3Bucket=codepipeline-us-east-1-782762410067,S3Key=$CODEBUILD_RESOLVED_SOURCE_VERSION.zip
      - aws elasticbeanstalk update-environment --environment-name callensights-app-env --version-label $CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - '**/*'
    