version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Running tests..."
      - python -m pytest
      - echo "Build completed on `date`"
  post_build:
    commands:
      - echo "Post-build started on `date`"
      - zip -r application.zip app/ .ebextensions/${ENV}.config
      - echo "Post-build completed on `date`"

artifacts:
  files: application.zip
