branch-defaults:
  feature/cns-fastapi:
    environment: Callensights-be-api-dev-dev
environment-defaults:
  Callensights-be-api-dev-env-1:
    branch: null
    repository: null
global:
  application_name: callensights-be-api-dev
  branch: null
  default_ec2_keyname: CNS-KP-Dev
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
